import { Deck } from "./Deck"
import { CardName } from "./cards/CardName"

export const deckMap: Record<string, Deck> = {
  testDeck: {
    id: "testDeck",
    name: "Test Deck",
    heroName: "Fire Hero",
    cardNames: [
      "Brash Splasher",
      "Brash Splasher",
      "Cave Swimmer",
      "Cave Swimmer",
      "Something Bandit",
      "Something Bandit",
      "Komodo Teacher",
      "Red Crab Brawler",
      "Red Crab Brawler",
      "Something Captain",
      "Pike Lancer",
      "Pike Lancer",
      "Sludge Amphibian",
      "Hydrus, Seaborn Titan",
      "Bed of Snakes",
      "Bed of Snakes",
      "Bonehide Mole",
      "Bonehide Mole",
      "Canyon Burrower",
      "Canyon Burrower",
      "Darkwoods Hyena",
      "Darkwoods Hyena",
      "Helix Stag",
      "Hyllophant",
      "Stegowulf",
      "Violet Sagebeast",
      "Violet Sagebeast",
      "Living Hillside",
      "Living Hillside",
      "Spirit Giant",
    ],
  },
  starterDeck: {
    id: "starterDeck",
    heroName: "Fire Hero",
    name: "My Deck",
    cardNames: [
      "Ember Foxling",
      "Ember Foxling",
      "Ember Foxling",
      "Flame Sentinel",
      "Flame Sentinel",
      "Dragon Cub",
      "Dragon Cub",
      "Smoldering Shot",
      "Smoldering Shot",
      "Neojia Tamer",
      "Neojia Tamer",
      "Monstrous Flamebeast",
      "Monstrous Flamebeast",
      "Saurongar The Smotherer",
      "Saurongar The Smotherer",
      "Spirit Giant",
      "Greenwing Caller",
      "Greenwing Caller",
      "Vengeful Flamewing",
      "Vengeful Flamewing",
      "Nyreth, Light Eater",
      "Golden Friend",
      "Something Raider",
      "Something Raider",
      "Emerald Makasaur",
      "Emerald Makasaur",
      "Elder Saurus",
      "Elder Saurus",
    ],
  },

  firstOpponent: {
    id: "firstOpponent",
    name: "First Opponent",
    heroName: "Fire Hero",
    cardNames: [
      "Brash Splasher",
      "Brash Splasher",
      "Cave Swimmer",
      "Merfin Yodeler",
      "Something Bandit",
      "Something Bandit",
      "Komodo Teacher",
      "Red Crab Brawler",
      "Red Crab Brawler",
      "Something Captain",
      "Sludge Amphibian",
      "Sludge Amphibian",
      "Hydrus, Seaborn Titan",
      "Bed of Snakes",
      "Bed of Snakes",
      "Bonehide Mole",
      "Canyon Burrower",
      "Canyon Burrower",
      "Darkwoods Hyena",
      "Darkwoods Hyena",
      "Helix Stag",
      "Huddolin",
      "Huddolin",
      "Stegowulf",
      "Living Hillside",
      "Living Hillside",
      "Golden Friend",
      "Something Raider",
      "Emerald Makasaur",
      "Elder Saurus",
    ],
  },
}
