import { Deck } from "./Deck"
import { CardName } from "./cards/CardName"

export const deckMap: Record<string, Deck> = {
  testDeck: {
    id: "testDeck",
    name: "Test Deck",
    cardNames: [
      "Fire Energy",
      "Fire Energy",
      "Fire Energy",
      "Fire Energy",
      "Fire Energy",

      "Fire Energy",
      "Fire Energy",
      "Fire Energy",
      "Fire Energy",
      "Fire Energy",

      "Air Energy",
      "Air Energy",
      "Air Energy",
      "Air Energy",
      "Air Energy",

      "Air Energy",
      "Air Energy",
      "Air Energy",
      "Air Energy",
      "Air Energy",

      "Joltbird Agent",
      "Joltbird Agent",
      "Joltbird Agent",
      "Joltbird Agent",
      "Joltbird Agent",

      "Joltbird Agent",
      "Joltbird Agent",
      "Joltbird Agent",
      "Joltbird Agent",
      "Joltbird Agent",

      "Joltbird Agent",
      "Joltbird Agent",
      "Joltbird Agent",
      "Joltbird Agent",
      "Joltbird Agent",

      "Dragon Cub",
      "Dragon Cub",
      "Dragon Cub",
      "Dragon Cub",
      "Dragon Cub",

      "Dragon Cub",
      "Dragon Cub",
      "Dragon Cub",
      "Dragon Cub",
      "Dragon Cub",

      "Dragon Cub",
      "Dragon Cub",
      "Dragon Cub",
      "Dragon Cub",
      "Dragon Cub",
    ],
  },
  starterDeck: {
    id: "starterDeck",
    name: "My Deck",
    cardNames: [
      "Fire Energy",
      "Fire Energy",
      "Fire Energy",
      "Fire Energy",
      "Fire Energy",
      "Fire Energy",
      "Fire Energy",
      "Fire Energy",
      "Fire Energy",
      "Fire Energy",
      "Ember Foxling",
      "Ember Foxling",
      "Flame Sentinel",
      "Dragon Cub",
      "Smoldering Shot",
      "Neojia Tamer",
      "Monstrous Flamebeast",
      "Monstrous Flamebeast",
      "Saurongar The Smotherer",
      "Spirit Giant",
      "Air Energy",
      "Air Energy",
      "Air Energy",
      "Air Energy",
      "Air Energy",
      "Air Energy",
      "Air Energy",
      "Air Energy",
      "Air Energy",
      "Air Energy",
      "Ancestral Presence",
      "Dazzling Fennec",
      "Eerie Vision",
      "Joltbird Agent",
      "Winged Bull",
      "Winged Bull",
      "Astral Caller",
      "Greenwing Caller",
      "Greenwing Caller",
      "Time Collapse",
      "Sonic Dragon",
      "Sonic Dragon",
      "Fairy Arsonist",
      "Startle",
      "Vengeful Flamewing",
      "Nyreth, Light Eater",
      "Golden Friend",
      "Something Raider",
      "Emerald Makasaur",
      "Elder Saurus",
    ],
  },

  firstOpponent: {
    id: "firstOpponent",
    name: "First Opponent",
    cardNames: [
      "Water Energy",
      "Water Energy",
      "Water Energy",
      "Water Energy",
      "Water Energy",
      "Water Energy",
      "Water Energy",
      "Water Energy",
      "Water Energy",
      "Water Energy",
      "Brash Splasher",
      "Brash Splasher",
      "Cave Swimmer",
      "Merfin Yodeler",
      "Something Bandit",
      "Something Bandit",
      "Komodo Teacher",
      "Red Crab Brawler",
      "Red Crab Brawler",
      "Something Captain",
      "Sludge Amphibian",
      "Sludge Amphibian",
      "Hydrus, Seaborn Titan",
      "Earth Energy",
      "Earth Energy",
      "Earth Energy",
      "Earth Energy",
      "Earth Energy",
      "Earth Energy",
      "Earth Energy",
      "Earth Energy",
      "Earth Energy",
      "Earth Energy",
      "Snake Network",
      "Snake Network",
      "Bonehide Mole",
      "Canyon Burrower",
      "Canyon Burrower",
      "Darkwoods Hyena",
      "Darkwoods Hyena",
      "Helix Stag",
      "Huddolin",
      "Huddolin",
      "Stegowulf",
      "Living Hillside",
      "Living Hillside",
      "Golden Friend",
      "Something Raider",
      "Emerald Makasaur",
      "Elder Saurus",
    ],
  },
}
