export type CardName =
  | "Bed of Snakes"
  | "Ember Foxling"
  | "Winged Bull"
  | "Elder Saurus"
  | "Merfin Yodeler"
  | "Spirit Giant"
  | "Nyreth, Light Eater"
  | "Komodo Teacher"
  | "Living Hillside"
  | "Stegowulf"
  | "Eerie Vision"
  | "Startle"
  | "Sonic Dragon"
  | "Cave Swimmer"
  | "Ancestral Presence"
  | "Dragon Cub"
  | "Hydrus, Seaborn Titan"
  | "Flame Sentinel"
  | "Brash Splasher"
  | "Joltbird Agent"
  | "Something Captain"
  | "Helix Stag"
  | "Neojia Tamer"
  | "Towering Owl"
  | "Opaldrake Thrasher"
  | "Saurongar the Smotherer"
  | "Time Collapse"
  | "Dazzling Fennec"
  | "Astral Caller"
  | "Pike Lancer"
  | "Hyllophant"
  | "Violet Sagebeast"
  | "Volcanic Shellster"
  | "Blooming Bingus"
  | "Spade Manta"
  | "Plasmite"
  | "Sky Dino"
  | "Little Imp Guy"
  | "Clucksworth"
  | "Little Chublet"
  | "Sun King Salamander"
  | "Hulking Menace"
  | "Treegre"
  | "Celestial Riftkeeper"
  | "Spewing Cavern"
  | "Cleansing Storm"
  | "Cloud Pegasus"
  | "Scrungy"
  | "Inferno Demon"
  | "Narples"
  | "Desert Crawler"
  | "Lion"
  | "Bouldering Brawler"
  | "Grassland Scout"
  | "Fire Blob"
  | "Pmochi"
  | "Stegobobo"
  | "Shark"
  | "Manta Sprite"
  | "Sol Guardian"
  | "Crab"
  | "Venus Fang"
  | "Ethereal Nightmother"
  | "Feathered Scrapper"
  | "Diabolical Cultist"
  | "Bad Chicken"
  | "Snail"
  | "Bubblebloop"
  | "Phoenix Dasher"
  | "Plewb"
  | "Wolf"
  | "Flame Demon"
  | "Owldus the Arcane"
  | "Mega Demigod"
  | "Molten Loaf"
  | "Eruption of Boulders"
  | "Cataclysm"
  | "Cowl Panther"
  | "Jebubblesaur"
  | "Nessinger"
  | "Deluvian Horror"
  | "Gnarldebeast"
  | "Icy Herder"
  | "Duskwood Ostrich"
  | "Spirit Woomlet"
  | "Bloodthirsty Bear"
