export type CardName =
  | "Golden Friend"
  | "Bed of Snakes"
  | "Ember Foxling"
  | "Winged Bull"
  | "Greenwing Caller"
  | "Elder Saurus"
  | "Vengeful Flamewing"
  | "Sludge Amphibian"
  | "Merfin Yodeler"
  | "Spirit Giant"
  | "Fairy Buckfly"
  | "Nyreth, Light Eater"
  | "Komodo Teacher"
  | "Living Hillside"
  | "Stegowulf"
  | "Eerie Vision"
  | "Startle"
  | "Sonic Dragon"
  | "Cave Swimmer"
  | "Darkwoods Hyena"
  | "Monstrous Flamebeast"
  | "Ancestral Presence"
  | "Canyon Burrower"
  | "Dragon Cub"
  | "Glikki Forager"
  | "Hydrus, Seaborn Titan"
  | "Flame Sentinel"
  | "Brash Splasher"
  | "Joltbird Agent"
  | "Something Bandit"
  | "Something Raider"
  | "Something Captain"
  | "Ilstrom, Tidal Inferno"
  | "Helix Stag"
  | "Bonehide Mole"
  | "Neojia Tamer"
  | "Huddolin"
  | "Opaldrake Thrasher"
  | "Smoldering Shot"
  | "Saurongar The Smotherer"
  | "Time Collapse"
  | "Fairy Arsonist"
  | "Emerald Makasaur"
  | "Dazzling Fennec"
  | "Astral Caller"
  | "Red Crab Brawler"
  | "Sicklehorn Grazer"
  | "Pike Lancer"
  | "Hyllophant"
  | "Violet Sagebeast"
  | "Moltsteed Racer"
  | "Volcanic Shellster"
