export type CardName =
  | "Fire Energy"
  | "Water Energy"
  | "Earth Energy"
  | "Air Energy"
  | "Golden Friend"
  | "Snake Network"
  | "Ember Foxling"
  | "Winged Bull"
  | "Greenwing Caller"
  | "Elder Saurus"
  | "Vengeful Flamewing"
  | "Sludge Amphibian"
  | "Merfin Yodeler"
  | "Spirit Giant"
  | "Fairy Buckfly"
  | "Nyreth, Light Eater"
  | "Komodo Teacher"
  | "Living Hillside"
  | "Stegowulf"
  | "Eerie Vision"
  | "Startle"
  | "Sonic Dragon"
  | "Cave Swimmer"
  | "Darkwoods Hyena"
  | "Monstrous Flamebeast"
