import { Deck } from "./Deck"
import { generateDeck } from "./generateDeck"

const STARTER_DECK: Deck = {
  id: "fireDeck",
  name: "Fire Deck",
  heroName: "Fire Hero",
  cardNames: [
    "Golden Friend",
    "Golden Friend",
    "Golden Friend",
    "Golden Friend",
    "Zardian Raider",
    "Zardian Raider",
    "Zardian Raider",
    "Zardian Raider",
    "Emerald Makasaur",
    "Emerald Makasaur",
    "Emerald Makasaur",
    "Emerald Makasaur",
    "Elder Saurus",
    "Elder Saurus",
    "Elder Saurus",
    "Elder Saurus",
    "Dragon Cub",
    "Dragon Cub",
    "Moltsteed Racer",
    "Moltsteed Racer",
  ],
}

export const deckMap: Record<string, Deck> = {
  testDeck: {
    id: "testDeck",
    name: "Test Deck",
    heroName: "Fire Hero",
    cardNames: [
      "Brash Splasher",
      "Brash Splasher",
      "Cave Swimmer",
      "Cave Swimmer",
      "Something Bandit",
      "Something Bandit",
      "Komodo Teacher",
      "Red Crab Brawler",
      "Red Crab Brawler",
      "Something Captain",
      "Pike Lancer",
      "Pike Lancer",
      "Sludge Amphibian",
      "Hydrus, Seaborn Titan",
      "Bed of Snakes",
      "Bed of Snakes",
      "Bonehide Mole",
      "Bonehide Mole",
      "Canyon Burrower",
      "Canyon Burrower",
      "Darkwoods Hyena",
      "Darkwoods Hyena",
      "Helix Stag",
      "Hyllophant",
      "Stegowulf",
      "Violet Sagebeast",
      "Violet Sagebeast",
      "Living Hillside",
      "Living Hillside",
      "Spirit Giant",
    ],
  },
  starterDeck: STARTER_DECK,

  firstOpponent: {
    id: "firstOpponent",
    name: "First Opponent",
    heroName: "Fire Hero",
    cardNames: [
      "Brash Splasher",
      "Brash Splasher",
      "Cave Swimmer",
      "Merfin Yodeler",
      "Something Bandit",
      "Something Bandit",
      "Komodo Teacher",
      "Red Crab Brawler",
      "Red Crab Brawler",
      "Something Captain",
      "Sludge Amphibian",
      "Sludge Amphibian",
      "Hydrus, Seaborn Titan",
      "Bed of Snakes",
      "Bed of Snakes",
      "Bonehide Mole",
      "Canyon Burrower",
      "Canyon Burrower",
      "Darkwoods Hyena",
      "Darkwoods Hyena",
      "Helix Stag",
      "Huddolin",
      "Huddolin",
      "Stegowulf",
      "Living Hillside",
      "Living Hillside",
      "Golden Friend",
      "Zardian Raider",
      "Emerald Makasaur",
      "Elder Saurus",
    ],
  },
}
